[package]
name = "proc-macro"
version = "0.1.0"
edition = "2021"


[dependencies]
proc-macro2 = "^1.0"
quote = "^1.0"
syn = "^1.0"
proc-macro-utils = { path = "../../../proc_macro_utils" }


[lib]
proc-macro = true
